### ISSUE TITLE
No support for accessing the mixpanel super properties

### ISSUE THREAD

**Issue by aanchal-adk** [john-doherty/mixpanel-lite#19]
We have a need to access the `distinct_id` super property but seems like the package doesn't currently support accessing of those super properties.

A `get_property` function that takes in a property name and returns its corresponding value would be really helpful.

**Comment by john-doherty** [comment]
Hi @aanchal-adk, feel free to submit a PR

**Comment by aanchal-adk** [comment]
@john-doherty I ran `npm run build` to generate `mixpanel-lite.min.js` as suggested in the README.md but the tests keep failing with different errors each time it's run.
![Screenshot from 2021-06-24 10-07-58](https://user-images.githubusercontent.com/22411120/123203080-86d28c00-d4d5-11eb-80e6-88fd213db48b.png)
![Screenshot from 2021-06-24 10-06-55](https://user-images.githubusercontent.com/22411120/123203091-8934e600-d4d5-11eb-8cc4-f54f39dc4818.png)
![Screenshot from 2021-06-24 10-07-30](https://user-images.githubusercontent.com/22411120/123203095-8a661300-d4d5-11eb-914d-06fb8ad87a44.png)

I can submit the PR once this is fixed but can't figure out why the counts in the tests are different every time test is run.

**Comment by john-doherty** [comment]
Thanks, @aanchal-adk, if you run the tests a few times they pass, which points to a race condition with online/offline events. I'll merge this in regardless and open a ticket to improve the tests
