### ISSUE TITLE
Mixpanel web: "We have not received any data yet"

### ISSUE THREAD

**Issue by john-doherty** [john-doherty/mixpanel-lite#2]
Hello all :wave:

I created this light weight version of mixpanel-js that supports offline mode so it could be used in a progressive web app, but I am having trouble getting it to work - the Mixpanel web app reports `We have not received any data yet`

It's using the [HTTP API](https://developer.mixpanel.com/docs/http) and was designed to include only the core functionality:

```js
// setup mixpanel
mixpanel.init('your-token-here');

// assign all future events to a user
mixpanel.identify('user@email.com');

// track an event
mixpanel.track('Your Event Name' {
    firstName: 'Optional event property 1',
    lastName: 'Optional event property 2'
});
```

I've included the full lifecycle below. What's confusing me is that each API request returns a success response :confused:
 
## Lifecycle

1) `mixpanel.init('your-token');`

__Request:__
HTTP GET https://api-js.mixpanel.com/track/?data=[base64EncodedData]&ip=1&verbose=1&_=[timestamp]

__Content:__
```json
{
   "event":"mp_page_view",
   "properties":{
      "$os":"Mac OS X",
      "$browser":"Chrome",
      "$current_url":"http://localhost:2000/",
      "$browser_version":78,
      "$screen_height":900,
      "$screen_width":1440,
      "mp_lib":"web",
      "$lib_version":"2.31.0",
      "time":1575884617.393,
      "distinct_id":"16eea0af6a462c-0fe130339ff27-3963720f-13c680-16eea0af6a5a00",
      "$device_id":"16eea0af6a462c-0fe130339ff27-3963720f-13c680-16eea0af6a5a00",
      "$initial_referrer":"$direct",
      "$initial_referring_domain":"$direct",
      "mp_page":"http://localhost:2000/",
      "mp_browser":"Chrome",
      "mp_platform":"Mac OS X",
      "token":"your-token"
   }
}
```

__Response:__
```json
{
   "error": null,
   "status": 1
}
```

2) `mixpanel.identify('user@email.com');`

__Request:__
HTTP GET https://api.mixpanel.com/track/?data=[base64EncodedData]&ip=1&verbose=1&_=[timestamp]

__Content:__
```json
{
   "event":"$identify",
   "properties":{
      "$os":"Mac OS X",
      "$browser":"Chrome",
      "$current_url":"http://localhost:2000/",
      "$browser_version":78,
      "$screen_height":900,
      "$screen_width":1440,
      "mp_lib":"web",
      "$lib_version":"2.31.0",
      "time":1575884618.17,
      "distinct_id":"user@email.com",
      "$device_id":"16eea0af6a462c-0fe130339ff27-3963720f-13c680-16eea0af6a5a00",
      "$initial_referrer":"$direct",
      "$initial_referring_domain":"$direct",
      "$user_id":"user@email.com",
      "$anon_distinct_id":"16eea0af6a462c-0fe130339ff27-3963720f-13c680-16eea0af6a5a00",
      "token":"your-token"
   }
}
```

__Response:__
```json
{
   "error": null,
   "status": 1
}
```

3) `mixpanel.track('It Works!')`

__Request:__
HTTP GET https://api.mixpanel.com/track/?data=[base64EncodedData]&ip=1&verbose=1&_=[timestamp]

__Content:__
```json
{
   "event":"It Works!",
   "properties":{
      "$os":"Mac OS X",
      "$browser":"Chrome",
      "$current_url":"http://localhost:2000/",
      "$browser_version":78,
      "$screen_height":900,
      "$screen_width":1440,
      "mp_lib":"web",
      "$lib_version":"2.31.0",
      "time":1575884618.138,
      "distinct_id":"user@email.com",
      "$device_id":"16eea0af6a462c-0fe130339ff27-3963720f-13c680-16eea0af6a5a00",
      "$initial_referrer":"$direct",
      "$initial_referring_domain":"$direct",
      "token":"your-token"
   }
}
```

__Response:__
```json
{
   "error": null,
   "status": 1
}
```

I am new to Mixpanel so it's very likely I am missing something.

Would love your help to figure it out :pray:

**Comment by jamessimone** [comment]
I’ve used Mixpanel in two production apps and both have employed the use of their Http api. There are two “gotchas” that you need to watch out for (and yes, I remember being frustrated by their responses’ lack of helpful info, although you can also appends ‘&verbose=1” to your query string to help.

Two things are missing from your requests: first of all, they should all be POST requests, not GET. Secondly, you need to append a “basic” auth header to your requests with the Base64 encoded API secret from your mixpanel project. (It may help you, as well, to add a colon after the base 64 encoded string.)

Thanks for your work on this and I hope this message helps! I have a lot of experience working with the Mixpanel HTTP api, and there are some fun lessons to be learned along the way.

**Comment by john-doherty** [comment]
Hi @jamessimone, thanks for the info.

I've had a look through [mixpanel-node](https://github.com/mixpanel/mixpanel-node/blob/master/lib/mixpanel-node.js#L156) source, and it appears the data is sent using a HTTP GET and without auth header.  Looks like HTTP POST is only uses when [posting a batch of events](https://github.com/mixpanel/mixpanel-node/blob/master/lib/mixpanel-node.js#L229).

Any more thoughts?

**Comment by jamessimone** [comment]
Hmm you may be right. Now that I’m thinking about it, the app that I was reviewing the code for was posting batches of events and mixpanel.people updates. I do have another app where I was sending singular events though - let me pull up the source code for that; I’m out running an errand at the moment but I will let you know soon!

**Comment by john-doherty** [comment]
Thank you @jamessimone!

**Comment by jamessimone** [comment]
@john-doherty I checked my other app - in both of them, I am POST'ing the data, even for singular events / updates. That is, seemingly, the only appreciable difference in the requests that we are generating. The only other thing that I can think of that might help is verifying you are sending the events using the right token. I have had the response come back from Mixpanel as successful when using the HTTP api even when not using the correct token. Let me know if that helps!

**Comment by john-doherty** [comment]
Turns out you need to send the following to the [/engage](https://developer.mixpanel.com/docs/http#section-profile-updates) before it will start logging events:

```json
{
   "$token": "your-token",
   "$distinct_id": "client-generated-uuid or email",
   "$set": {
      "$email": "user@email.com"
   }
 }
```

I'm honestly not sure that is mentioned in any docs, I was just running through the API trying different things and that appears to have resolved it. If anyone has any more info I'd love to hear it!

Thanks again for your help @jamessimone

**Comment by tdumitrescu** [comment]
You definitely don't need to send /engage updates in order to see tracked events. You might see a "no data" message if you're looking at part of the UI that only shows user profile data (like the Explore report), as that data only gets updated via /engage. But normal /track events should be visible in https://mixpanel.com/report/insights within a few minutes of sending track requests to a new project.

**Comment by evanjmoss** [comment]
One other thing to mention is that you'll get a response of 1 even if you use the wrong token.
